---
- name: Configure main nginx config file
  become: true
  template:
    src: '{{ jc_nginx_main_template }}'
    dest: '/etc/nginx/nginx.conf'
  notify:
    - restart nginx

- name: Configure django nginx config file
  become: true
  template:
    src: '{{ jc_nginx_app_template }}'
    dest: '/etc/nginx/sites-available/{{ jc_project_config_name }}.conf'
  notify:
    - restart nginx

- name: Enable nginx app
  become: true
  file:
    src: '/etc/nginx/sites-available/{{ jc_project_config_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ jc_project_config_name }}.conf'
    state: link
  notify:
    - restart nginx

- name: Create socket directory
  become: true
  file:
    path: '{{ jc_dir_uwsgi_socket }}'
    state: directory

- name: Configure uwsgi app
  become: true
  template:
      src: '{{ jc_uwsgi_app_template }}'
      dest: '/etc/uwsgi/apps-available/{{ jc_project_config_name }}.ini'
  notify:
    - restart uwsgi

- name: Enable uwsgi app
  become: true
  file:
      dest: '/etc/uwsgi/apps-enabled/{{ jc_project_config_name }}.ini'
      src: '/etc/uwsgi/apps-available/{{ jc_project_config_name }}.ini'
      state: link
  notify:
    - restart uwsgi