---
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ waj_app_user }}'
  with_items:
    - '{{ waj_projects_directory }}'
    - '{{ waj_projects_directory }}/{{ waj_project_name }}'
    - '{{ waj_awstats_dir }}'

- name: Check if current version exists
  stat: 
    path: '{{ waj_projects_directory }}/{{ waj_project_name }}/current'
  register: currentversion

- name: Create version directory
  file:
    path: '{{ waj_projects_directory }}/{{ waj_project_name }}/{{ waj_app_version }}'
    state: directory
    owner: '{{ waj_app_user }}'
  register: newversion

- name: Change recursively all permissions 
  file:
    dest: '{{ waj_projects_directory }}/{{ waj_project_name }}/{{ waj_app_version }}'
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
    mode: u=rwX,g=rwX,o=rX
    recurse: yes

- name: Clone git repository    
  become: true
  become_user: '{{ waj_git_user }}'
  git:
    repo: '{{ waj_git_repository }}'
    dest: '{{ waj_git_project_path }}'
    clone: '{{ waj_git_clone }}'
    update: '{{ waj_git_update }}'
    force: '{{ waj_git_force }}'
    track_submodules: yes
    version: '{{ waj_git_version }}'
  notify:
    - reload uwsgi

- name: Deploy config
  template:
    src: 'settings.py.j2'
    dest: '{{ waj_git_project_path }}/{{ waj_project_title }}/{{ waj_project_title }}/settings.py'
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
  notify:
    - reload uwsgi

- name: Create log directory
  file:
    path: '{{ waj_git_project_path }}/{{ waj_project_title }}/log'
    state: directory
    owner: '{{ waj_app_user }}'

- name: Deploy superuser config
  template:
    src: 'import_users.py.j2'
    dest: '{{ waj_git_project_path }}/{{ waj_project_title }}/account_app/management/commands/import_users.py'
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
  notify:
    - reload uwsgi

- name: Copy media files 
  copy:
    src: '{{ waj_media_files }}'
    dest: '{{ waj_git_project_path }}/{{ waj_project_title }}'
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
    mode: u=rw,g=rw,o=r
    directory_mode: yes

- name: Copy previous media files 
  synchronize:
    src: '{{ waj_project_path }}/{{ waj_project_title }}/media/files'
    dest: '{{ waj_git_project_path }}/{{ waj_project_title }}/media/files'
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"
  when:
    - newversion.changed
    - currentversion.stat.islnk is defined

- name: Copy database from current version to new version
  copy:
    src: '{{ waj_project_path }}/{{ waj_project_title }}/db.sqlite3'
    dest: '{{ waj_git_project_path }}/{{ waj_project_title }}/db.sqlite3'
    remote_src: yes
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
    mode: u=rw,g=rw,o=r
  when:
    - (newversion.changed) or (waj_force_copy_database)
    - (not waj_import_commandments) or (not waj_import_media)
    - waj_db_type != "mariadb"
    - currentversion.stat.islnk is defined

- name: Install pip dependencies
  pip:
    name: uWSGI
    virtualenv: '{{ waj_python_env }}'
    virtualenv_python: python3

- name: Change recursively all permissions 
  file:
    dest: '{{ waj_projects_directory }}/{{ waj_project_name }}/{{ waj_app_version }}'
    owner: '{{ waj_app_user }}'
    group: '{{ waj_app_group }}'
    mode: u=rwX,g=rwX,o=rX
    recurse: yes

- name: Install requirements
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash install.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_install_requirements

- name: Update database
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash update_database.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_update_database

- name: Create application admin user
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash create_admin_user.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_create_admin_user

- name: Import Commandments & Media
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash IMPORT.sh -q -d -f"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_import_commandments

- name: Update translation files
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash update_translation_files.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_update_translation_files

- name: Auto translate files
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash auto_translate_files.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_auto_translate_files

- name: Clean Thumbnail Cache
  become: true
  become_user: '{{ waj_app_user }}'
  shell: "bash clean_thumbnail_cache.sh"
  args:
    chdir: "{{ waj_git_project_path }}/{{ waj_project_title }}"
    executable: /bin/bash
  when:
    - waj_clean_thumbnail_cache
    - newversion.changed

- name: Point symlink to new version
  file:
    src: '{{ waj_projects_directory }}/{{ waj_project_name }}/{{ waj_app_version }}'
    dest: '{{ waj_projects_directory }}/{{ waj_project_name }}/current'
    state: link
  notify: restart uwsgi
