---
- name: Install system dependencies
  become: true
  apt:
    name: "{{ jc_packages }}"
    state: present

- name: Add the git user with a bash shell
  user:
    name: '{{ jc_git_user }}'
    shell: /bin/bash
    group: '{{ jc_app_group }}'
