---
# Database installation & configuration.
- include_tasks: mariadb-variables.yml
  when: jc_db_type == "mariadb"
- include_tasks: mariadb-setup.yml
  when: jc_db_type == "mariadb"
- include_tasks: mariadb-configure.yml
  when: jc_db_type == "mariadb"
- include_tasks: mariadb-secure-installation.yml
  when: jc_db_type == "mariadb"
- include_tasks: mariadb-post.yml
  when: jc_db_type == "mariadb"

- name: Configure facts
  set_fact:
    jc_dir_uwsgi_socket: '/run/uwsgi/app/{{ jc_project_name }}'

- name: More facts
  set_fact:
    jc_uwsgi_socket: '{{ jc_dir_uwsgi_socket }}/socket'
  changed_when: False
  notify:
    - start nginx
    - start uwsgi

- include_tasks: deps.yml
- include_tasks: deploy.yml
- include_tasks: config.yml
