---

- name: Ensure MySQL database is present.
  mysql_db:
    name: "{{ mysql_db_waj_name }}"
    collation: "{{ mysql_db_waj_collation | default('utf8_general_ci') }}"
    encoding: "{{ mysql_db_waj_encoding | default('utf8') }}"
    # login_unix_socket: "{{ mysql_socket }}"
    state: "{{ mysql_db_waj_state | default('present') }}"

- name: Ensure MySQL user is present.
  mysql_user:
    name: "{{ mysql_user_waj_name }}"
    host: "{{ mysql_user_waj_host | default('localhost') }}"
    password: "{{ mysql_user_waj_password }}"
    priv: "{{ mysql_user_waj_priv | default('*.*:USAGE') }}"
    state: "{{ mysql_user_waj_state | default('present') }}"
    # login_unix_socket: "{{ mysql_socket }}"
    append_privs: "{{ mysql_user_waj_append_privs | default('no') }}"
    encrypted: "{{ mysql_user_waj_encrypted | default('no') }}"
  no_log: true

- name: Configure automysqlbackup
  replace:
    path: "/etc/default/automysqlbackup"
    regexp: "/etc/mysql/debian.cnf"
    replace: "{{ mysql_root_home }}/.my.cnf"